name = "AProgrammingLanguageForScientists"
uuid = "4626a9c4-1b15-11e9-3752-ad032b099e3c"
authors = ["Harry Scholes <harry.scholes.16@ucl.ac.uk>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
